### ISSUE TITLE
ステージ選択画面にステージ一覧を表示する

### ISSUE THREAD

**Issue by ak03120** [ak03120/quiz-appl#9]
## 概要 (Summary):
モックデータをバイディングさせて表示する
## 誰が使うか (For whom):
ユーザー
## 何のために or どのように実装するか (For what):
1. typesフォルダを作成しその中にinterface用のファイルを作って型記述する。

2. Stage Interfaceを使用してステージ一覧のモックデータを選択画面のtsファイルに作成する。

3. *ngForを使ってモックデータをバイディングして表示する。
*ngForは以下リンクを参考にしてみてください。
https://li.dott.dev/fa8U
## 達成目標:
モックデータが表示できていること

**Comment by hikaru-nakamura-thedott** [comment]
表示しているステージのカードをコンポーネント化しよう！
